version: "2"
services:

  python:
    build:
      context: anaconda-rodeo
    image: anaconda-rodeo:3.4-0.4.4
    ports:
      - 5000:5000
    links:
      - datastore
    volumes:
      - ./src:/home/shared/rodeo

  datastore:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./datastore:/data

  datastore-ui:
    image: mongo-express
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: "puppy hair = win!"
      ME_CONFIG_MONGODB_SERVER: datastore
    ports:
      - 8081:8081
    links:
      - datastore
